#!/usr/bin/env bash
ME=$(readlink -f $0)
BASE=$(dirname $ME)
SRCBIN=${BASE}/src/usr/local/bin
SCRIPT=/tmp/buildscript.$$

comskip_build_script() {
cat <<EOD
#!/usr/bin/env bash
echo Cloning comskip git repo
git clone https://github.com/erikkaashoek/Comskip /comskip
cd /comskip && ./autogen.sh && export CFLAGS=-w && ./configure && make && make install
chmod 755 /usr/local/bin/comskip
chmod 755 /usr/local/bin/comskip-gui
chown $(id -u):$(id -g) /usr/local/bin/comskip
chown $(id -u):$(id -g) /usr/local/bin/comskip-gui
EOD
}

if [ ! -d ${SRCBIN} ]; then
    mkdir -p ${SRCBIN} || {
        echo "Error creating source bin directory: ${SRCBIN}"
        exit
    }
fi

echo Updating slackpost
SLACKSRC=${HOME}/dev/golang/bin/slackpost
[ -f ${SRCBIN}/slackpost ] && mv ${SRCBIN}/slackpost{,.sav}
[ -f ${SLACKSRC} ] && cp ${SLACKSRC} ${SRCBIN}/slackpost
chmod 755 ${SRCBIN}/slackpost

echo Updating comchap
curl https://raw.githubusercontent.com/BrettSheleski/comchap/master/comchap > ${SRCBIN}/comchap
curl https://raw.githubusercontent.com/BrettSheleski/comchap/master/comcut > ${SRCBIN}/comcut
chmod 755 ${SRCBIN}/comchap
chmod 755 ${SRCBIN}/comcut

echo Updating comskip
[ -f ${SRCBIN}/comskip ] && mv ${SRCBIN}/comskip{,.sav}
[ -f ${SRCBIN}/comskip-gui ] && mv ${SRCBIN}/comskip-gui{,.sav}
comskip_build_script > ${SCRIPT}
chmod 755 ${SCRIPT}
docker run --rm --name build-comskip -it -u root -v ${SCRIPT}:/buildscript -v ${SRCBIN}:/usr/local/bin mbrown/buildenv:latest bash -c /buildscript | tee ${BASE}/build.log
[ -f ${SCRIPT} ] && rm ${SCRIPT}

chmod -R 0755 ${BASE}/src
chmod 0644 ${BASE}/src/usr/local/etc/* 
