#!/usr/bin/env bash
ME=$(readlink -f $0)
BASE=$(dirname $ME)
COMCHAP=${BASE}/comchap
COMSKIP=${BASE}/comskip

if [ ! -d ${COMCHAP} ]; then
    mkdir -p ${COMCHAP}
fi

if [ -d ${COMCHAP} ]; then
    echo Updating comchap
    curl https://raw.githubusercontent.com/BrettSheleski/comchap/master/comchap > ${COMCHAP}/comchap
    curl https://raw.githubusercontent.com/BrettSheleski/comchap/master/comcut > ${COMCHAP}/comcut
    chmod 755 ${COMCHAP}/comchap
    chmod 755 ${COMCHAP}/comcut
fi

if [ -d ${COMSKIP} ]; then
    echo Updating comskip
    cp ${BASE}/build-comskip ${COMSKIP}
    [ -f ${COMSKIP}/comskip ] && mv ${COMSKIP}/comskip{,.sav}
    [ -f ${COMSKIP}/comskip-gui ] && mv ${COMSKIP}/comskip-gui{,.sav}
    docker run --rm --name build-comskip -it -v ${COMSKIP}:/usr/local/bin ubuntu:latest bash -c /usr/local/bin/build-comskip| tee ${COMSKIP}/build.log
else
    echo Comskip directory not found, creating new
    mkdir ${COMSKIP}
    cp ${BASE}/build-comskip ${COMSKIP}
    docker run --rm --name build-comskip -it -v ${COMSKIP}:/usr/local/bin ubuntu:latest bash -c /usr/local/bin/build-comskip| tee ${COMSKIP}/build.log
fi

